---
- name: Create cluster dir
  ansible.builtin.file:
    path: "/home/kni/clusterconfigs/{{ global_config.cluster_name }}"
    state: directory
    mode: "0755"
- name: Render install-config
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "/home/kni/clusterconfigs/{{ global_config.cluster_name }}/install-config.yaml"
- name: Render agent-config
  ansible.builtin.template:
    src: agent-config.yaml.j2
    dest: "/home/kni/clusterconfigs/{{ global_config.cluster_name }}/agent-config.yaml"
# TODO: create ISO, upload to provider, wait for bootstrap/install
